### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by DLTKKevinW** [braathen/qv-webticket#1]
Have you experienced issue with SSL? 
The accesspoint is https://qlik.domain.com

When SSL is on, error out with message:
Error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Any idea what might be the issue? Thanks!

I did try to enable trusted host etc...

**Comment by braathen** [comment]
I have now disabled verification for certificates, making untrusted or self-generated certificated work. The GitHub repo is updated now and v1.0.2 of NuGet packages will have the fix shortly.
