### ISSUE TITLE
User gets prompted for login

### ISSUE THREAD

**Issue by DLTKKevinW** [braathen/qv-webticket#2]
Thanks for fixing SSL issue, now we are not getting certificate error anymore. But we are getting prompted for login. This works fine when testing internally, but not when this deployed to internet.

Here is our setup:
1. User go thru internet via https://qlik.domain.com (this is an alias redirect, there is a different URL which is very long);
2. Two servers (web server: qlikwebsvr1 & app server: qlikappsvr1);

So in code,  two URL that I have been changing back and forth, but still get nowhere -
I have used: 

public static string QlikViewServerURL = @"https://qlikwebsvr1/QVAJAXZFC/getwebticket.aspx?";

in ticket configuration URL for return URL -

AccessPointUri = new Uri ("https://qlik.domain.com/qlikview"),

In our situation, what should be the right URL address?

Thanks!

**Comment by braathen** [comment]
If you get a prompted for credentials it means you have not disabled Windows Authentication on /QvAjaxZfc/ and /QlikView/ folders in IIS. The easiest way to get webticketing working is to set everything to Anonymous Authentication and use TrustedIP in config.xml to allow the ticket request.
